language: node_js
node_js:
  - "7"
env:
  global:
    - CC_TEST_REPORTER_ID=9d45d734205700e5c34190347ce487e44c329373a61ef8ba1eae4903b745809f
rvm:
  - 2.2.0
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - npm run coverage
  